export const CHANGE_SEARCH_VALUE = "CHANGE_SEARCH_VALUE";

export const LOAD_ALL_CERTIFICATES = "LOAD_ALL_CERTIFICATES";
export const VERIFY_CERTIFICATE = "VERIFY_CERTIFICATE";
export const SELECT_SIGNER_CERTIFICATE = "SELECT_SIGNER_CERTIFICATE";

export const VERIFY_SIGNATURE = "VERIFY_SIGNATURE";
export const CHANGE_SIGNATURE_ENCODING = "CHANGE_SIGNATURE_ENCODING";
export const CHANGE_SIGNATURE_DETACHED = "CHANGE_SIGNATURE_DETACHED";
export const CHANGE_SIGNATURE_TIMESTAMP = "CHANGE_SIGNATURE_TIMESTAMP";
export const CHANGE_SIGNATURE_OUTFOLDER = "CHANGE_SIGNATURE_OUTFOLDER";

export const SELECT_FILE = "SELECT_FILE";
export const ACTIVE_FILE = "ACTIVE_FILE";
export const DELETE_FILE = "DELETE_FILE";

export const SUCCESS = "_SUCCESS";
export const FAIL = "_FAIL";
export const START = "_START";

export const DER = "DER";
export const BASE64 = "BASE-64";
