export const CHANGE_SEARCH_VALUE = "CHANGE_SEARCH_VALUE";

export const LOAD_ALL_CERTIFICATES = "LOAD_ALL_CERTIFICATES";
export const VERIFY_CERTIFICATE = "VERIFY_CERTIFICATE";
export const SELECT_SIGNER_CERTIFICATE = "SELECT_SIGNER_CERTIFICATE";

export const VERIFY_SIGNATURE = "VERIFY_SIGNATURE";
export const CHANGE_SIGNATURE_ENCODING = "CHANGE_SIGNATURE_ENCODING";
export const CHANGE_SIGNATURE_DETACHED = "CHANGE_SIGNATURE_DETACHED";
export const CHANGE_SIGNATURE_TIMESTAMP = "CHANGE_SIGNATURE_TIMESTAMP";
export const CHANGE_SIGNATURE_OUTFOLDER = "CHANGE_SIGNATURE_OUTFOLDER";

export const ADD_RECIPIENT_CERTIFICATE = "ADD_RECIPIENT_CERTIFICATE";
export const DELETE_RECIPIENT_CERTIFICATE = "DELETE_RECIPIENT_CERTIFICATE";
export const CHANGE_ECRYPT_ENCODING = "CHANGE_ECRYPT_ENCODING";
export const CHANGE_DELETE_FILES_AFTER_ENCRYPT = "CHANGE_DELETE_FILES_AFTER_ENCRYPT";
export const CHANGE_ARCHIVE_FILES_BEFORE_ENCRYPT = "CHANGE_ARCHIVE_FILES_BEFORE_ENCRYPT";
export const CHANGE_ENCRYPT_OUTFOLDER = "CHANGE_ENCRYPT_OUTFOLDER";

export const SELECT_FILE = "SELECT_FILE";
export const ACTIVE_FILE = "ACTIVE_FILE";
export const DELETE_FILE = "DELETE_FILE";

export const SUCCESS = "_SUCCESS";
export const FAIL = "_FAIL";
export const START = "_START";

export const DER = "DER";
export const BASE64 = "BASE-64";

export const CHANGE_LOCALE = "CHANGE_LOCALE";
export const RU = "RU";
export const EN = "EN";

export const MY = "MY";
export const ADDRESS_BOOK = "AddressBook";
export const ROOT = "ROOT";
export const TRUST = "TRUST";
export const CA = "CA";
export const REQUEST = "Request";

export const PROVIDER_SYSTEM = "PROVIDER_SYSTEM";
export const PROVIDER_MICROSOFT = "PROVIDER_MICROSOFT";
export const PROVIDER_CRYPTOPRO = "PROVIDER_CRYPTOPRO";
