export const ERROR_LOAD_TRUSTED_CRYPTO = "ERROR_LOAD_TRUSTED_CRYPTO";
export const NOT_INSTALLED_CSP = "NOT_INSTALLED_CSP";
export const ERROR_CHECK_CSP_LICENSE = "ERROR_CHECK_CSP_LICENSE";
export const NO_GOST_2001 = "NO_GOST_2001";
export const ERROR_CHECK_CSP_PARAMS = "ERROR_CHECK_CSP_PARAMS";
export const NO_CRYPTOARM_LICENSE = "NO_CRYPTOARM_LICENSE";
export const NO_CORRECT_CRYPTOARM_LICENSE = "NO_CORRECT_CRYPTOARM_LICENSE";
export const NO_HAVE_CERTIFICATES_WITH_KEY = "NO_HAVE_CERTIFICATES_WITH_KEY";

export const WARNING = "WARNING";
export const BUG = "BUG";
